name: module_phuhuynh
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  go_router: ^13.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/
    - assets/home/home1.jpg
    - assets/home/home2.jpg
    - assets/home/home3.jpg
    - assets/home/home4.jpg
    - assets/home/home5.jpg
    - assets/home/home6.jpg
    - assets/home/home7.jpg



  uses-material-design: true
